### ISSUE TITLE
creation of macOS box with 10.12.4 is stuck on installation

### ISSUE THREAD

**Issue by mroswald** [bitrise-tools/replica#7]
Hi,

I'm currently running into an error which is filed to [Virtualbox](https://www.virtualbox.org/ticket/16644). It seems that it's not possible at the moment to create a box with macOS >= 10.12.4 but I saw at bitrise the [boxes use 10.12.4](https://github.com/bitrise-io/bitrise.io/blob/master/system_reports/osx-xcode-8.3.x.log#L489). Are you internally using another tooling to create the boxes or do you have a workaround for that? Is using VMware an option (I saw that virtualbox is hardcoded in replica)

Thanks,
Mark

**Comment by viktorbenei** [comment]
Hi,

You can find the currently tested version at https://github.com/bitrise-tools/replica/blob/master/TESTED_TOOL_VERSIONS.md - unfortunately we didn't have enough time to work on `replica` lately..

> Are you internally using another tooling to create the boxes or do you have a workaround for that?

Indeed we don't use `replica` for creating production VMs for bitrise.io; we create those directly in the production "private cloud" system (we use vSphere there right now).

**Comment by mroswald** [comment]
Thanks!

**Comment by viktorbenei** [comment]
Any time! Hopefully we can get back to working on `replica` soon - we do have plans for it, we're just working on other features first ;)
